# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  commands:
    - pip install poetry
    # First modify all pyproject.toml files to use exact versions
    - cp pyproject.toml pyproject.toml.bak
    - |
      sed -i \
        -e "s|{ path = \"core\", develop = true }|\"0.4.9\"|g" \
        -e "s|{ path = \"tools\", develop = true }|\"0.4.9\"|g" \
        -e "s|{ path = \"coding\", develop = true }|\"0.4.9\"|g" \
        -e "s|{ path = \"web\", develop = true }|\"0.4.9\"|g" \
        -e "s|{ path = \"router\", develop = true }|\"0.4.9\"|g" \
        -e "s|{ path = \"examples\", develop = true }|\"0.4.9\"|g" \
        pyproject.toml
    # Build packages in order following build.sh approach
    # First build core
    - cd core && poetry build && cd ..
    - pip install core/dist/*.whl
    # Build and install other packages
    - cd tools && poetry build && cd .. && pip install tools/dist/*.whl
    - cd coding && poetry build && cd .. && pip install coding/dist/*.whl
    - cd web && poetry build && cd .. && pip install web/dist/*.whl
    - cd router && poetry build && cd .. && pip install router/dist/*.whl
    - cd examples && poetry build && cd .. && pip install examples/dist/*.whl
    # Build the meta-package
    - touch ./just_agents/__init__.py
    - poetry build
    - pip install dist/*.whl
    - rm ./just_agents/__init__.py

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt