name: just-agents #has dependencies for all subpackages
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests
  - pytest>=8.3.3 #for tests
  - typer>=0.12.5 #for CLI
  - twine #for publishing
  - pip:
      - litellm>=1.50.1
      - numpydoc
      - semanticscholar>=0.8.4
      - git+https://github.com/vndee/llm-sandbox.git #llm-sandbox for sendbox testing, using main branch because of bug in pip-ed version
      - Mako>=1.3.5 #optional, might be deleted in the future