name: just-agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - loguru>=0.7.2
  - requests
  - pytest>=8.3.1 #for tests
  - typer>=0.12.3 #for CLI
  - twine #for publishing
  - pip:
      - litellm>=1.42.4
      - numpydoc
      - semanticscholar>=0.8.4
      - Mako>=1.3.5
      - qwen-agent>=0.0.6