name: just-agents-core #has dependencies only for core just-agents library
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - requests
  - pytest>=8.3.3 #for tests
  - typer>=0.13.0 #for CLI
  - pip
  - pip:
      - litellm>=1.52.14
      - numpydoc