name: just-agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - requests
  - pytest>=8.3.3 #for tests
  - typer>=0.12.5 #for CLI
  - twine #for publishing
  - pip:
      - litellm>=1.48.11
      - numpydoc
      - semanticscholar>=0.8.4
      - Mako>=1.3.5 #optional, might be deleted in the future