name: just-agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - loguru
  - requests
  - pytest #for tests
  - typer #for CLI
  - twine #for publishing
  - starlette
  - jupyter
  - pip:
      - litellm>=1.40.78
      - numpydoc
      - semanticscholar>=0.8.1
      - Mako>=1.3.5