name: just-agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - loguru
  - click
  - requests
  - pytest
  - typer
  - pip:
      - litellm>=1.40.6
      - jupyter
      - numpydoc
      - semanticscholar>=0.8.1
      - Mako>=1.3.5