[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "just-agents"
version = "0.3.0"
description = "Just Agents"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Alex Karmazin", email = "karmazinalex@gmail.com" },
]
maintainers = [
    { name = "Anton Kulaga", email = "antonkulaga@gmail.com" },
]
keywords = ["python", "llm", "science", "review", "agents", "AI"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]
dependencies = [
    "litellm>=1.52.9",
    "Deprecated>=1.2.15",
    "requests",
    "numpydoc", # https://github.com/BerriAI/litellm/issues/6810
]
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/longevity-genie/just-agents"
"Bug Tracker" = "https://github.com/longevity-genie/just-agents/issues"
Documentation = "https://just-agents.readthedocs.io/"

[project.optional-dependencies]
tools = [
    "semanticscholar>=0.8.4",
    "typer>=0.13.0",
]
coding = [
    "llm-sandbox>=0.1.4",
]
web = [
    "loguru",
    "fastapi",
    "uvicorn",
    "thefuzz"
]

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["just_agents*"]

[project.scripts]
just-agents = "just_agents.cli:main"