[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "just-agents-all"
version = "0.3.3"
description = "Just Agents - Complete Package with All Components"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Alex Karmazin", email = "karmazinalex@gmail.com" },
]
maintainers = [
    { name = "Anton Kulaga", email = "antonkulaga@gmail.com" },
]
dependencies = [
    "just-agents>=0.3.3",
    "just-agents-web>=0.3.3",
    "just-agents-tools>=0.3.3",
    "just-agents-router>=0.3.3",
    "just-agents-coding>=0.3.3",
    "just-agents-examples>=0.3.3",
]
license = {text = "MIT"}

[project.urls]
Homepage = "https://github.com/longevity-genie/just-agents"
"Bug Tracker" = "https://github.com/longevity-genie/just-agents/issues"
Documentation = "https://just-agents.readthedocs.io/"

[tool.setuptools]
packages = [
    "just_agents",
    "just_agents_web",
    "just_agents_tools",
    "just_agents_coding",
    "just_agents_router",
    "just_agents_examples"
]