agent_profiles:
  BaseAgentSchemaExample:
    class_qualname: just_agents.base_agent.BaseAgent
    completion_max_tries: 2
    completion_remove_key_on_error: true
    description: Generic all-purpose AI agent
    drop_params: true
    on_response: []
    streaming_method: openai
    system_prompt: You are a helpful AI assistant
  SecretaryAgent:
    autoload_from_yaml: false
    class_qualname: just_agents_router.secretary_agent.SecretaryAgent
    completion_max_tries: 2
    completion_remove_key_on_error: true
    description: Generic all-purpose AI agent
    drop_params: true
    exclude_list:
    - include_list
    - exclude_list
    - refresh_list
    - extra_dict
    - filter_list
    extra_dict:
      personality_traits: Agent's personality traits go here
    filter_list:
    - system_prompt
    - tools
    - llm_options
    - exclude_list
    - refresh_list
    - extra_dict
    include_list:
    - shortname
    - description
    - system_prompt
    - tools
    - llm_options
    - class_hierarchy
    - class_qualname
    llm_options:
      model: gpt-4o-mini
      temperature: 0.0
    streaming_method: openai
    system_prompt: "\n    You are a skilled AI assistant specializing in analysis\
      \ and description of AI agents. \n    You are tasked with generation of a minimalistic\
      \ and concise yet detail-rich profile for an AI agent, based on the AVAILABLE_ATTRIBUTES,\
      \ \n    including 'system_prompt', 'llm_options' and any other. Your task is\
      \ to fill in values of a JSON-formatted profile \n    that matches the PROFILE_UPDATE_TEMPLATE\
      \ provided below. Values of the template describe what output is expected for\
      \ each field. \n    Only populate fields based on the well-established information,\
      \ don't make up anything. \n    Double-check that the output contains only a\
      \ valid JSON with all the fields specified in PROFILE_UPDATE_TEMPLATE. \n  \
      \  Never include any additional text or explanations in your reply.\n    "
