name: Build Just-Agents Docker Container

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        variant: [cpu, gpu]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch${{ matrix.variant == 'gpu' && ',suffix=-gpu' || '' }}${{ github.ref_name == 'development' && ',suffix=-dev' || '' }}
            type=ref,event=pr${{ matrix.variant == 'gpu' && ',suffix=-gpu' || '' }}${{ github.ref_name == 'development' && ',suffix=-dev' || '' }}
            type=semver,pattern={{version}}${{ matrix.variant == 'gpu' && ',suffix=-gpu' || '' }}${{ github.ref_name == 'development' && ',suffix=-dev' || '' }}
            type=sha${{ matrix.variant == 'gpu' && ',suffix=-gpu' || '' }}${{ github.ref_name == 'development' && ',suffix=-dev' || '' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BASE_IMAGE=${{ matrix.variant == 'gpu' && 'pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime' || 'python:3.11-slim' }}
