name: run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11"]

    env:
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          
      - name: Install packages in correct order
        run: |
          cd core && poetry install --with dev && cd ..
          if [ -d "coding" ]; then cd coding && poetry install --with dev && cd ..; fi
          if [ -d "web" ]; then cd web && poetry install --with dev && cd ..; fi
          if [ -d "tools" ]; then cd tools && poetry install --with dev && cd ..; fi
          if [ -d "router" ]; then cd router && poetry install --with dev && cd ..; fi
          if [ -d "examples" ]; then cd examples && poetry install --with dev; fi

      - name: Run tests
        run: poetry run python -m pytest
        working-directory: .
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
